# Generated by Django 4.0.1 on 2022-08-20 11:08

import ckeditor.fields
import colorfield.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=40, unique=True)),
                ('icon', models.ImageField(upload_to='gender_icon/')),
                ('icon_color', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Heigth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdealMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idealmatch', models.CharField(max_length=40, unique=True)),
                ('icon', models.ImageField(upload_to='idealMatch_icon/')),
                ('icon_color', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40, unique=True)),
                ('icon', models.ImageField(upload_to='maritalstatus_icon/')),
                ('icon_color', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('icon', models.ImageField(upload_to='idealMatch_icon/')),
                ('icon_bg_color', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passion', models.CharField(max_length=40, unique=True)),
                ('slug_field', models.SlugField(max_length=220)),
                ('icon', models.ImageField(upload_to='passion_icon/')),
                ('icon_color', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=500, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('country_code', models.CharField(blank=True, max_length=8, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('birth_date', models.DateField(default='1999-12-15')),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('is_media', models.BooleanField(default=False)),
                ('is_marital_status', models.BooleanField(default=False)),
                ('is_gender', models.BooleanField(default=False)),
                ('image', models.URLField(blank=True, null=True)),
                ('is_tall', models.BooleanField(default=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('is_location', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('is_interest_in', models.BooleanField(default=False)),
                ('is_passion', models.BooleanField(default=False)),
                ('is_idealmatch', models.BooleanField(default=False)),
                ('selfie', models.CharField(blank=True, max_length=255, null=True)),
                ('govt_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_govt_id_verified', models.BooleanField(default=False)),
                ('is_register_user_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(blank=True, max_length=8, null=True)),
                ('auth_tokens', models.TextField(blank=True, null=True)),
                ('is_complete_profile', models.BooleanField(default=False)),
                ('active_reseaon', models.TextField(blank=True, null=True)),
                ('show_profile', models.IntegerField(choices=[(0, 'all'), (1, 'friend'), (2, 'onlyme')], default=2)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_gender', to='account.gender')),
                ('idealmatch', models.ManyToManyField(blank=True, db_column='IdealMatch', to='account.IdealMatch')),
                ('interest_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest_in_gender', to='account.gender')),
                ('marital_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_merital_status', to='account.maritalstatus')),
                ('passion', models.ManyToManyField(blank=True, db_column='passion', to='account.Passion')),
                ('tall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_height', to='account.heigth')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
