# Generated by Django 4.0 on 2022-01-17 10:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=40, unique=True)),
                ('icon', models.URLField(blank=True, null=True)),
                ('icon_color', models.CharField(max_length=40)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdealMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idealmatch', models.CharField(max_length=40, unique=True)),
                ('icon', models.URLField(blank=True, null=True)),
                ('icon_color', models.CharField(max_length=40)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=40, unique=True)),
                ('icon', models.URLField(blank=True, null=True)),
                ('icon_color', models.CharField(max_length=40)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40, unique=True)),
                ('icon', models.URLField(blank=True, null=True)),
                ('icon_color', models.CharField(max_length=40)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=500, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('country_code', models.CharField(blank=True, max_length=8, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('birth_date', models.DateField(default='1999-12-15')),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('body_type', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, default=180.34, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('citylat', models.DecimalField(blank=True, decimal_places=6, default='-2.0180319', max_digits=9, null=True)),
                ('citylong', models.DecimalField(blank=True, decimal_places=6, default='52.5525525', max_digits=9, null=True)),
                ('address', models.CharField(blank=True, max_length=900, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('first_count', models.IntegerField(blank=True, default=0, help_text='It is 0, if the user is totally new and 1 if the user has saved his standard once', null=True)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_gender', to='account.gender')),
                ('relationship_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_merital_status', to='account.maritalstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_image_profile', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interest', to='account.interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inter', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserIdealMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('idealmatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_match', to='account.idealmatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ideal', to='account.user')),
            ],
        ),
    ]
