# Generated by Django 4.0 on 2022-01-04 09:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=500, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateField(default='1999-12-15')),
                ('mobile', models.CharField(max_length=10)),
                ('country_code', models.CharField(max_length=8)),
                ('otp', models.CharField(max_length=4)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
