# Generated by Django 4.0.1 on 2022-02-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passion_in',
            field=models.ManyToManyField(blank=True, related_name='passion_data', to='account.Passion'),
        ),
    ]
