# Generated by Django 4.0.1 on 2022-09-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_verified_status',
            field=models.IntegerField(choices=[(0, 'panding'), (1, 'inprogress'), (2, 'verified')], default=0),
        ),
    ]
