# Generated by Django 4.0 on 2022-01-20 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useridealmatch',
            name='idealmatch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_match', to='account.idealmatch'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userpassion',
            name='passion',
        ),
        migrations.AddField(
            model_name='userpassion',
            name='passion',
            field=models.ManyToManyField(related_name='user_Passion', to='account.Passion'),
        ),
    ]
