# Generated by Django 4.0 on 2022-01-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
