# Generated by Django 4.0.1 on 2022-04-26 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermedia',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpassion',
            name='passion',
        ),
        migrations.RemoveField(
            model_name='userpassion',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserIdealMatch',
        ),
        migrations.DeleteModel(
            name='UserMedia',
        ),
        migrations.DeleteModel(
            name='UserPassion',
        ),
    ]
