# Generated by Django 4.0.1 on 2022-09-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_user_verified_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='govt_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='selfie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
