# Generated by Django 4.0.1 on 2022-02-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_first_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='height_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_in_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='location_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='relationship_status_field',
            field=models.BooleanField(default=False),
        ),
    ]
