# Generated by Django 4.0 on 2022-01-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_useridealmatch_idealmatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpassion',
            name='passion',
        ),
        migrations.AddField(
            model_name='userpassion',
            name='passion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_Passion', to='account.passion'),
            preserve_default=False,
        ),
    ]
