# Generated by Django 4.0 on 2022-01-14 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_usermedia_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterest',
            name='interest',
        ),
        migrations.AddField(
            model_name='userinterest',
            name='interest',
            field=models.ManyToManyField(related_name='user_interest', to='account.Interest'),
        ),
        migrations.CreateModel(
            name='ProfileCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewcount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_count', to='account.user')),
            ],
        ),
    ]
