# Generated by Django 4.0.1 on 2022-02-01 10:38

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_gender_field_user_height_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='icon_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='idealmatch',
            name='icon_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='icon_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='passion',
            name='icon_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
