# Generated by Django 4.0.1 on 2022-04-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_usermedia_user_remove_userpassion_passion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_tokens',
            field=models.TextField(blank=True, null=True),
        ),
    ]
