# Generated by Django 4.0.1 on 2022-02-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_passion_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passion_in',
            new_name='passion',
        ),
    ]
