# Generated by Django 4.0.1 on 2022-02-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_gender_icon_color_alter_idealmatch_icon_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='icon',
            field=models.ImageField(default=1, upload_to='gender_icon/'),
            preserve_default=False,
        ),
    ]
