# Generated by Django 4.0.1 on 2022-11-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_govt_id_url_user_profile_image_user_selfie_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='govt_id_url',
            field=models.ImageField(blank=True, null=True, upload_to='govt_id_image/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='selfie_url',
            field=models.ImageField(blank=True, null=True, upload_to='selfie_image/'),
        ),
    ]
