# Generated by Django 4.0.1 on 2022-04-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_auth_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_complete_profile',
            field=models.BooleanField(default=False),
        ),
    ]
