# Generated by Django 4.0.1 on 2022-02-02 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_passion_in_user_passion'),
    ]

    operations = [
        migrations.AddField(
            model_name='passion',
            name='slug_field',
            field=models.SlugField(default=django.utils.timezone.now, max_length=220),
            preserve_default=False,
        ),
    ]
