# Generated by Django 4.0.1 on 2022-05-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_show_private_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='show_private_post',
            new_name='show_profile',
        ),
    ]
