# Generated by Django 4.0.1 on 2022-02-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_passion_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passion',
            field=models.ManyToManyField(blank=True, db_column='passion', null=True, to='account.Passion'),
        ),
    ]
