# Generated by Django 4.0.1 on 2022-02-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_passion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idealmatch',
            field=models.ManyToManyField(blank=True, db_column='IdealMatch', to='account.IdealMatch'),
        ),
        migrations.AddField(
            model_name='user',
            name='idealmatch_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='passion_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='passion',
            field=models.ManyToManyField(blank=True, db_column='passion', to='account.Passion'),
        ),
    ]
