# Generated by Django 4.0.1 on 2022-05-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_show_private_post_user_show_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='show_profile',
            field=models.IntegerField(choices=[(0, 'all'), (1, 'friend'), (2, 'onlyme')], default=0),
        ),
    ]
