# Generated by Django 4.0.1 on 2022-02-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_idealmatch_user_idealmatch_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_profile',
            new_name='is_media_field',
        ),
    ]
