# Generated by Django 4.0.1 on 2022-02-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_is_profile_user_is_media_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heigth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
