# Generated by Django 4.0.1 on 2022-05-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_show_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_reseaon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
