# Generated by Django 4.0.1 on 2022-02-07 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_heigth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='heights',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_height', to='account.heigth'),
        ),
    ]
