# Generated by Django 4.0.1 on 2022-02-07 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_heights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
    ]
