# Generated by Django 4.0.1 on 2022-02-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_user_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='govt_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_govt_id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='selfie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
