# Generated by Django 4.0.1 on 2022-02-21 07:41

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_is_register_user_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('icon', models.ImageField(upload_to='idealMatch_icon/')),
                ('icon_bg_color', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gender_field',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='height_field',
            new_name='is_gender',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='idealmatch_field',
            new_name='is_idealmatch',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='interest_in_field',
            new_name='is_interest_in',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_media_field',
            new_name='is_location',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_phone_verified',
            new_name='is_marital_status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='location_field',
            new_name='is_media',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='passion_field',
            new_name='is_passion',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='relationship_status_field',
            new_name='is_tall',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='relationship_status',
            new_name='marital_status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='heights',
            new_name='tall',
        ),
        migrations.RemoveField(
            model_name='user',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='education',
        ),
    ]
