# Generated by Django 4.0.1 on 2022-04-11 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='title', max_length=255, null=True)),
                ('message', models.TextField(blank=True, default='messages', null=True)),
                ('post', models.TextField(blank=True, null=True)),
                ('uploadvideo', models.TextField(blank=True, null=True)),
                ('is_view_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_like_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_share_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_view', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postsview', to='post.postupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postview', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_share', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postshare', to='post.postupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postshare', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlike', to='post.postupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlike', to='account.user')),
            ],
        ),
    ]
