# Generated by Django 4.0.1 on 2022-08-20 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='title', max_length=255, null=True)),
                ('message', models.TextField(blank=True, default='messages', null=True)),
                ('post', models.TextField(blank=True, null=True)),
                ('uploadvideo', models.TextField(blank=True, null=True)),
                ('is_view_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_like_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_share_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('post_report', models.BooleanField(blank=True, default=False, null=True)),
                ('is_private', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('show_public_post', models.IntegerField(choices=[(0, 'all'), (1, 'friend'), (2, 'onlyme')], default=0)),
                ('show_private_post', models.IntegerField(choices=[(0, 'all'), (1, 'friend'), (2, 'onlyme')], default=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_view', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postsview', to='post.postupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postview', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postreplike', to='post.postupload')),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(blank=True, default=False, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlike', to='post.postupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlike', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postimages', to='post.postupload')),
            ],
        ),
    ]
