# Generated by Django 4.0.1 on 2022-04-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='is_like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
