# Generated by Django 4.0 on 2022-01-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liker',
        ),
        migrations.RemoveField(
            model_name='like',
            name='petId',
        ),
        migrations.RemoveField(
            model_name='postupload',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='postupload',
            name='share_count',
        ),
        migrations.RemoveField(
            model_name='postupload',
            name='view_count',
        ),
        migrations.AddField(
            model_name='postupload',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='post_likes', to='account.User'),
        ),
        migrations.AddField(
            model_name='postupload',
            name='shares',
            field=models.ManyToManyField(blank=True, default=0, related_name='post_shares', to='account.User'),
        ),
        migrations.AddField(
            model_name='postupload',
            name='views',
            field=models.ManyToManyField(blank=True, default=0, related_name='post_view', to='account.User'),
        ),
        migrations.DeleteModel(
            name='CountLike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='PostData',
        ),
    ]
