# Generated by Django 4.0.1 on 2022-02-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postupload_uploadvedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postupload',
            name='post',
            field=models.TextField(blank=True, null=True),
        ),
    ]
