# Generated by Django 4.0.1 on 2022-11-09 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postupload_user_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_post_image', models.ImageField(blank=True, null=True, upload_to='user_post_image/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('post_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpostiamge', to='post.postupload')),
            ],
        ),
    ]
