# Generated by Django 4.0 on 2022-01-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_like_liker_remove_like_petid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postupload',
            name='likes',
        ),
        migrations.AddField(
            model_name='postupload',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='postupload',
            name='shares',
        ),
        migrations.AddField(
            model_name='postupload',
            name='shares',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='postupload',
            name='views',
        ),
        migrations.AddField(
            model_name='postupload',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
