# Generated by Django 4.0.1 on 2022-04-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postreport_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postupload',
            name='post_report',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
