# Generated by Django 4.0.1 on 2022-12-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postimageupload_user_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimageupload',
            name='user_post_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
