# Generated by Django 4.0.1 on 2023-01-12 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_govt_id_url_alter_user_profile_image_and_more'),
        ('post', '0005_postimageupload_user_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreport',
            name='report_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reposrtuserpost', to='account.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postreport',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postreplike', to='post.postupload'),
        ),
    ]
