# Generated by Django 4.0.1 on 2022-02-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_is_view_postlike_is_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postupload',
            name='is_like_count',
        ),
        migrations.RemoveField(
            model_name='postupload',
            name='is_share_count',
        ),
        migrations.RemoveField(
            model_name='postupload',
            name='is_view_count',
        ),
    ]
