# Generated by Django 4.0.1 on 2022-04-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postupload_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postupload',
            name='is_private',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
