# Generated by Django 4.0.1 on 2023-01-12 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_govt_id_url_alter_user_profile_image_and_more'),
        ('post', '0006_postreport_report_user_alter_postreport_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreport',
            name='report_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposrtuserpost', to='account.user'),
        ),
    ]
