# Generated by Django 4.0 on 2022-01-19 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_postreaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreaction',
            name='is_like',
        ),
        migrations.RemoveField(
            model_name='postreaction',
            name='is_share',
        ),
        migrations.RemoveField(
            model_name='postreaction',
            name='is_view',
        ),
    ]
