# Generated by Django 4.0.1 on 2022-02-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_postupload_is_like_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postupload',
            name='is_like_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='postupload',
            name='is_share_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='postupload',
            name='is_view_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
