# Generated by Django 4.0.1 on 2022-05-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_postupload_show_private_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postupload',
            name='show_private_post',
            field=models.IntegerField(choices=[(0, 'all'), (1, 'friend'), (2, 'onlyme')], default=0),
        ),
        migrations.AlterField(
            model_name='postupload',
            name='show_public_post',
            field=models.IntegerField(choices=[(0, 'all'), (1, 'friend'), (2, 'onlyme')], default=0),
        ),
    ]
