# Generated by Django 4.0.1 on 2022-02-28 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_mastertable_rename_gender_field_user_is_active_and_more'),
        ('post', '0007_postupload_is_like_count_postupload_is_share_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='usertitle', max_length=255, null=True)),
                ('message', models.TextField(blank=True, default='messages', null=True)),
                ('post', models.TextField(blank=True, null=True)),
                ('uploadvideo', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userposts', to='account.user')),
            ],
        ),
    ]
