# Generated by Django 4.0.1 on 2023-01-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_postreport_report_user_newpostreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPostReport',
        ),
    ]
