# Generated by Django 4.0.1 on 2023-01-12 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_govt_id_url_alter_user_profile_image_and_more'),
        ('post', '0009_delete_newpostreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newpostreplike', to='post.postupload')),
                ('report_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newreposrtuserpost', to='account.user')),
            ],
        ),
    ]
