# Generated by Django 4.0 on 2022-01-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_rename_likes_postupload_is_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postupload',
            old_name='is_likes',
            new_name='is_like',
        ),
        migrations.RenameField(
            model_name='postupload',
            old_name='is_shares',
            new_name='is_share',
        ),
        migrations.RenameField(
            model_name='postupload',
            old_name='is_views',
            new_name='is_view',
        ),
    ]
