# Generated by Django 4.0.1 on 2022-03-01 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_mastertable_rename_gender_field_user_is_active_and_more'),
        ('post', '0010_userpostslike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpostlike', to='post.userpost'),
        ),
        migrations.AlterField(
            model_name='userpostlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpostlike', to='account.user'),
        ),
        migrations.AlterField(
            model_name='userpostslike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernewposts', to='post.userpost'),
        ),
        migrations.AlterField(
            model_name='userpostslike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newuserposts', to='account.user'),
        ),
    ]
