# Generated by Django 4.0 on 2022-01-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_rename_is_likes_postupload_is_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postupload',
            name='is_like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='postupload',
            name='is_share',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='postupload',
            name='is_view',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
