# Generated by Django 4.0.1 on 2023-01-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_newpostreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='postupload',
            name='is_soft_delete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
