# Generated by Django 4.0.1 on 2022-03-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_userpostlike_post_alter_userpostlike_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpostlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='userpostlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpostslike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='userpostslike',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
        migrations.DeleteModel(
            name='UserPostLike',
        ),
        migrations.DeleteModel(
            name='UserPostsLike',
        ),
    ]
