# Generated by Django 4.0.1 on 2023-01-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_postupload_is_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpostreport',
            name='is_report',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newpostreport',
            name='repost_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
