# Generated by Django 4.0 on 2022-01-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_mediapost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postupload',
            name='is_like',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='postupload',
            name='is_share',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='postupload',
            name='is_view',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
