# Generated by Django 4.0 on 2022-01-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_mediapost_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapost',
            name='post',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
