# Generated by Django 4.0 on 2022-01-20 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_alter_mediapost_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediareaction',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
