# Generated by Django 4.0 on 2022-01-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_mediareaction_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediapost',
            old_name='post',
            new_name='media',
        ),
    ]
