# Generated by Django 4.0 on 2022-01-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_alter_postupload_is_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postupload',
            old_name='is_like',
            new_name='islike',
        ),
        migrations.RenameField(
            model_name='postupload',
            old_name='is_share',
            new_name='isshare',
        ),
        migrations.RenameField(
            model_name='postupload',
            old_name='is_view',
            new_name='isview',
        ),
    ]
