# Generated by Django 4.0 on 2022-01-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_rename_is_like_postupload_islike_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postupload',
            old_name='islike',
            new_name='is_like',
        ),
        migrations.RenameField(
            model_name='postupload',
            old_name='isshare',
            new_name='is_share',
        ),
        migrations.RemoveField(
            model_name='postupload',
            name='isview',
        ),
        migrations.AddField(
            model_name='postupload',
            name='is_view',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
