# Generated by Django 4.0 on 2022-01-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_postlike_postshare_postview_delete_postreaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediareaction',
            name='media',
        ),
        migrations.RemoveField(
            model_name='mediareaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='MediaPost',
        ),
        migrations.DeleteModel(
            name='MediaReaction',
        ),
    ]
