# Generated by Django 4.0.1 on 2022-08-20 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=300, null=True)),
                ('media', models.TextField(blank=True, max_length=500, null=True)),
                ('media_video', models.TextField(blank=True, max_length=500, null=True)),
                ('view_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('like_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('share_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('media_report', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('show_media_photo', models.IntegerField(choices=[(0, 'all'), (1, 'friend'), (2, 'onlyme')], default=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='MediaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_caption', models.CharField(blank=True, max_length=300, null=True)),
                ('media_video', models.TextField(blank=True, max_length=500, null=True)),
                ('view_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('like_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('show_media_video', models.IntegerField(choices=[(0, 'all'), (1, 'friend'), (2, 'onlyme')], default=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='MediaPostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.CharField(blank=True, max_length=300, null=True)),
                ('media', models.TextField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('media_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermedia.mediapost')),
            ],
        ),
        migrations.CreateModel(
            name='MediaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(blank=True, default=False, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermedia.mediapost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
