# Generated by Django 4.0.1 on 2022-02-15 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediapost',
            name='is_media',
        ),
    ]
