# Generated by Django 4.0.1 on 2022-04-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='media_video',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
