# Generated by Django 4.0.1 on 2022-11-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='user_media',
            field=models.ImageField(blank=True, null=True, upload_to='user_media_image/'),
        ),
    ]
