# Generated by Django 4.0.1 on 2022-12-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0002_mediapost_user_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='user_media_video',
            field=models.ImageField(blank=True, null=True, upload_to='user_media_image/'),
        ),
    ]
