# Generated by Django 4.0.1 on 2022-04-20 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_country'),
        ('usermedia', '0002_mediapost_media_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_caption', models.CharField(blank=True, max_length=300, null=True)),
                ('media_video', models.TextField(blank=True, max_length=500, null=True)),
                ('view_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('like_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
