# Generated by Django 4.0.1 on 2022-04-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0003_mediavideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='media_report',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MediaPostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.CharField(blank=True, max_length=300, null=True)),
                ('media', models.TextField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('media_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermedia.mediapost')),
            ],
        ),
    ]
