# Generated by Django 4.0.1 on 2022-12-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0003_mediapost_user_media_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediapost',
            name='user_media_video',
        ),
        migrations.AddField(
            model_name='mediapost',
            name='media_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
