# Generated by Django 4.0.1 on 2022-05-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0004_mediapost_media_report_mediapostreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='show_private_post',
            field=models.CharField(choices=[(0, 'all'), (1, 'friend'), (2, 'onlyme')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='mediavideo',
            name='show_private_post',
            field=models.CharField(choices=[(0, 'all'), (1, 'friend'), (2, 'onlyme')], default=0, max_length=1),
        ),
    ]
