# Generated by Django 4.0.1 on 2022-05-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0005_mediapost_show_private_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediapost',
            old_name='show_private_post',
            new_name='show_media_photo',
        ),
        migrations.RenameField(
            model_name='mediavideo',
            old_name='show_private_post',
            new_name='show_media_video',
        ),
    ]
