# Generated by Django 4.0.1 on 2022-05-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0006_rename_show_private_post_mediapost_show_media_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapost',
            name='show_media_photo',
            field=models.IntegerField(choices=[(0, 'all'), (1, 'friend'), (2, 'onlyme')], default=0),
        ),
        migrations.AlterField(
            model_name='mediavideo',
            name='show_media_video',
            field=models.IntegerField(choices=[(0, 'all'), (1, 'friend'), (2, 'onlyme')], default=0),
        ),
    ]
