# Generated by Django 4.0.1 on 2022-05-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0008_alter_mediapost_show_media_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialike',
            name='is_like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
