# Generated by Django 4.0.1 on 2023-01-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlist',
            name='is_soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
