# Generated by Django 4.0.1 on 2022-10-08 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_user_govt_id_alter_user_selfie'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDisLikeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=False)),
                ('craeted', models.DateTimeField(auto_now=True)),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dislike_profile', to='account.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='account.user')),
            ],
        ),
    ]
