# Generated by Django 4.0 on 2022-01-20 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postuserupdate',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostUserReact',
        ),
        migrations.DeleteModel(
            name='PostUserUpdate',
        ),
    ]
