# Generated by Django 4.0 on 2021-12-29 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ideamatch',
        ),
        migrations.AddField(
            model_name='profile',
            name='ideamatch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.userideamatch'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userinterest',
        ),
        migrations.AddField(
            model_name='profile',
            name='userinterest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.userinterest'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='profile',
            name='usermedia',
        ),
        migrations.AddField(
            model_name='profile',
            name='usermedia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.usermedia'),
            preserve_default=False,
        ),
    ]
