# Generated by Django 4.0 on 2021-12-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_profile_ideamatch_profile_ideamatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterest',
            name='user',
        ),
        migrations.AddField(
            model_name='userinterest',
            name='interest',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
