# Generated by Django 4.0 on 2021-12-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_userinterest_user_userinterest_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='slug',
            field=models.SlugField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='interest',
            field=models.CharField(max_length=200),
        ),
    ]
