# Generated by Django 4.0 on 2021-12-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userinterest_slug_alter_userinterest_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userideamatch',
            name='user',
        ),
        migrations.AddField(
            model_name='userideamatch',
            name='interest',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userideamatch',
            name='slug',
            field=models.SlugField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
