# Generated by Django 4.0 on 2021-12-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_userideamatch_user_userideamatch_interest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userideamatch',
            old_name='interest',
            new_name='ideamatch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ideamatch',
        ),
        migrations.AddField(
            model_name='profile',
            name='ideamatch',
            field=models.ManyToManyField(to='main.UserIdeaMatch'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userinterest',
        ),
        migrations.AddField(
            model_name='profile',
            name='userinterest',
            field=models.ManyToManyField(to='main.UserInterest'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='usermedia',
        ),
        migrations.AddField(
            model_name='profile',
            name='usermedia',
            field=models.ManyToManyField(to='main.UserMedia'),
        ),
    ]
