# Generated by Django 4.0.1 on 2023-01-02 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postimageupload_user_post_type'),
        ('masterdata', '0006_notificationdata_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdata',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postsview_notification', to='post.postupload'),
        ),
    ]
