# Generated by Django 4.0.1 on 2022-09-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequest',
            name='is_follow_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
