# Generated by Django 4.0 on 2022-01-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_userinterest_interest_userinterest_interest_and_more'),
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='friends',
        ),
        migrations.AddField(
            model_name='friendlist',
            name='friends',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='account.user'),
            preserve_default=False,
        ),
    ]
