# Generated by Django 4.0.1 on 2022-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_remove_friendrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='show_friend',
            field=models.CharField(choices=[(0, 'all'), (1, 'friend'), (2, 'onlyme')], default=0, max_length=1),
        ),
    ]
