# Generated by Django 4.0.1 on 2022-02-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_rename_timestamp_followrequest_create_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='is_active',
            new_name='friendrequestsent',
        ),
    ]
