# Generated by Django 4.0 on 2022-01-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_faq_followrequest_followaccept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
