# Generated by Django 4.0.1 on 2022-05-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0004_alter_friendlist_show_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='show_friend',
            field=models.IntegerField(choices=[(0, 'all'), (1, 'friend'), (2, 'onlyme')], default=2),
        ),
    ]
