# Generated by Django 4.0.1 on 2022-02-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0004_friendlist_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='followaccept',
            name='is_follow_accepted',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
