# Generated by Django 4.0.1 on 2022-03-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0005_followaccept_is_follow_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrequest',
            name='is_active',
        ),
        migrations.AddField(
            model_name='followrequest',
            name='is_follow',
            field=models.BooleanField(default=False),
        ),
    ]
