# Generated by Django 4.0.1 on 2022-03-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0006_remove_followrequest_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='friendrequestsent',
            field=models.BooleanField(default=False),
        ),
    ]
