# Generated by Django 4.0.1 on 2022-03-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0007_alter_friendrequest_friendrequestsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followaccept',
            name='is_follow_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
